### ISSUE TITLE
can't build with cargo on windows because of space in folder name

### ISSUE THREAD

**Issue by dsisnero** [artichoke/artichoke#591] opened 2020-03-23 20:10 UTC
My work computer - can't change my account name and it has spaces 'Dominic E Sisneros' .  When trying to build with 
cargo install --git https://github.com/artichoke/artichoke --locked artichoke

It errors because of the space in name.  All file paths need to be surrounded by quotes

``` 

  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\load.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\load.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\cstime.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\cstime.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\cutime.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\cutime.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\peak.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\peak.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\size.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\size.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\stime.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\stime.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\total.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\total.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\utime.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\runner\\utime.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\lib\\benchmark_driver\\output\\driver.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\lib\\benchmark_driver\\output\\driver.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\aobench.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\aobench.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\binary_trees.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\binary_trees.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\gcbench.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\gcbench.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\hash1.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\hash1.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\hash2.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\hash2.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\null.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\null.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\pentomino.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\pentomino.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\rdoc.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\rdoc.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\redblack.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\redblack.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\ring.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\ring.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\basictest\\runner.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\basictest\\runner.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\a16a5f8\\artichoke-backend\\vendor\\ruby\\basictest\\test.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installElR5PS\\release\\build\\artichoke-backend-5f5a1ef69c033543\\out\\artichoke-mruby\\ruby\\basictest\\test.rb"
(in C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installElR5PS/release/build/artichoke-backend-5f5a1ef69c033543/out/artichoke-mruby/mruby)
rake aborted!
Don't know how to rake C:\Users\DOMINI~1\AppData\Local\Temp\cargo-installElR5PS\release\build\artichoke-backend-5f5a1ef69c033543\out\artichoke-mruby\mruby-build/sys/mrbgems/mruby-error/../../../../../../../../../../../../../Dominic E Sisneros/AppData/Local/Temp/cargo-installElR5PS/release/build/artichoke-backend-5f5a1ef69c033543/out/artichoke-mruby/mruby/mrbgems/mruby-error/src/exception.o


--- stderr
thread 'main' panicked at 'minirake failed', F:\windows\tools\rust\.cargo\git\checkouts\artichoke-c12ffc01676ba375\a16a5f8\artichoke-backend\build.rs:204:13
```

**Comment by lopopolo** [comment] 2020-03-23 20:56
Thanks for the report. The bug is in the `mruby` build.

I’ll investigate whether this reproduces on macOS when there are spaces in the folder name.

I do not have a windows machine to test with.

**Comment by lopopolo** [comment] 2020-03-24 03:47
I was able to reproduce this on my local (mac) system when the build path contains a space. Fix coming soon.

**Comment by lopopolo** [comment] 2020-03-24 03:59
Proposed fix is in GH-592.

**Comment by lopopolo** [comment] 2020-03-24 17:27
@dsisnero I merged a fix in GH-592. Let me know if it works for you. You should be able to run the same command and install artichoke now.

**Comment by dsisnero** [comment] 2020-03-24 19:18
Still errors on windows with rake

ull.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\d5441ee\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\pentomino.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installitIM5k\\release\\build\\artichoke-backend-98f883e4b11feae0\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\pentomino.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\d5441ee\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\rdoc.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installitIM5k\\release\\build\\artichoke-backend-98f883e4b11feae0\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\rdoc.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\d5441ee\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\redblack.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installitIM5k\\release\\build\\artichoke-backend-98f883e4b11feae0\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\redblack.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\d5441ee\\artichoke-backend\\vendor\\ruby\\benchmark\\gc\\ring.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installitIM5k\\release\\build\\artichoke-backend-98f883e4b11feae0\\out\\artichoke-mruby\\ruby\\benchmark\\gc\\ring.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\d5441ee\\artichoke-backend\\vendor\\ruby\\basictest\\runner.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installitIM5k\\release\\build\\artichoke-backend-98f883e4b11feae0\\out\\artichoke-mruby\\ruby\\basictest\\runner.rb"
  copy: "F:\\windows\\tools\\rust\\.cargo\\git\\checkouts\\artichoke-c12ffc01676ba375\\d5441ee\\artichoke-backend\\vendor\\ruby\\basictest\\test.rb" -> "C:\\Users\\DOMINI~1\\AppData\\Local\\Temp\\cargo-installitIM5k\\release\\build\\artichoke-backend-98f883e4b11feae0\\out\\artichoke-mruby\\ruby\\basictest\\test.rb"
(in C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby)
rake aborted!
Don't know how to rake C:\Users\DOMINI~1\AppData\Local\Temp\cargo-installitIM5k\release\build\artichoke-backend-98f883e4b11feae0\out\artichoke-mruby\mruby-build/sys/mrbgems/mruby-error/../../../../../../../../../../../../../Dominic E Sisneros/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/mrbgems/mruby-error/src/exception.o
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:179:in `[]'
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:104:in `block (2 levels) in invoke'
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:104:in `select'
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:104:in `block in invoke'
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:101:in `each'
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:101:in `invoke'
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:541:in `run'
C:/Users/DOMINI~1/AppData/Local/Temp/cargo-installitIM5k/release/build/artichoke-backend-98f883e4b11feae0/out/artichoke-mruby/mruby/minirake:620:in `<main>'

--- stderr
thread 'main' panicked at 'minirake failed', F:\windows\tools\rust\.cargo\git\checkouts\artichoke-c12ffc01676ba375\d5441ee\artichoke-backend\build.rs:205:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by lopopolo** [comment] 2020-03-26 04:12
Unfortunately I do not have a Windows machine so I can't reproduce the failure.

Eventually the solution is to publish pre-built binaries. This idea is partially captured in https://github.com/artichoke/artichoke/issues/287.

I'm marking this ticket as help wanted.

**Comment by lopopolo** [comment] 2020-03-26 04:16
A short term solution might be to pre-compile the mruby yacc source and check that in to avoid invoking rake altogether. We are already diverged enough from mruby upstream that this might be ok.

**Comment by dsisnero** [comment] 2020-04-01 19:27
I just posted a pull request to mruby that will fix the space problems.
https://github.com/mruby/mruby/pull/4959

**Comment by dsisnero** [comment] 2020-04-02 14:06
This pull request has been merged https://github.com/mruby/mruby/commit/068b16a352bc19a403ac24fe9d2d9b69cabe2e0b

Do you pull each time from mruby ?  If not, can you pull now to get this change in? Thanks

**Comment by lopopolo** [comment] 2020-04-02 15:39
We do not pull regularly from upstream mruby anymore as our fork has diverged in hard to manage ways (surgery on GC and Array).

I tried to rebase from upstream and ended up with a segfaulting test build.

If you'd like to apply your patch, the fork is here https://github.com/artichoke/mruby.

**Comment by lopopolo** [comment] 2020-04-02 15:40
It would probably be easiest if you forked artichoke and applied your patch there, because then you could verify cargo install works by `cargo install`ing your fork

**Comment by lopopolo** [comment] 2021-01-07 20:40
I'm closing this issue since there's been no response from the reporter.

The following updates have been made since this issue was reported:

- mruby has been upgraded to the latest 2.1.2 release.
- Pre-built binaries for windows are available at https://github.com/artichoke/nightly/releases.

If this remains an issue, please file a new issue with reproduction steps.

**Closed by lopopolo** 2021-01-07 20:40 UTC
Labels: A-build, B-mruby, C-bug, E-help-wanted, O-windows
